### PR TITLE
New design applied to the sample, updated styles and layout

### PR DESCRIPTION
**Pull request by didiepetrova**

### CODE REVIEW

**Comment by TsvetinaIvanova** [comment]
There is a typo in the commit message, and as a whole, I would recommend a slightly more descriptive message.

**Comment by TsvetinaIvanova** [comment]
:+1:

**Comment by AntonDobrev** [comment]
A few remarks:
 - We do not need the  <title>Custom URL Scheme</title> in the index.html
- No support for WP - remove this from the README - _developed with WP SDK 8.1_
- Since we do not support WP - I am guessing that is why the cordova.wp is not present 

Otherwise :+1:

**Comment by didiepetrova** [comment]
Comments addressed.

**Pull request merged**
